### Default variable file for telegram_unified_service ###
environment: "dev"
telemetry_url: "http://telemetry-service:9001"
telemetry_log_enabled: "true"

namespace: ""
dockerhub: ""

activity_api_base_url: "http://activitysakhi-service:8000"
story_api_base_url: "http://storysakhi-service:8000"

ut_repository: "sakhi_telegram_unified_service"
ut_image_tag: "latest"
ut_log_level: "INFO"
ut_telegram_bot_name: ""
ut_telegram_bot_token: ""
ut_concurrent_updates: 50
ut_pool_timeout: 90
ut_connection_pool_size: 512
ut_supported_languages: en,bn,gu,hi,kn,ml,mr,or,pa,ta,te
ut_telegram_base_url: "https://dev.ejp.sunbird.org/api/webhook"
ut_uvicorn_workers: 4
ut_connect_timeout: 300
ut_read_timeout: 15
ut_write_time_out: 10

replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 8000
  targetport: 8000
strategy:
  type: RollingUpdate
  maxsurge: 25
  maxunavailable: 25

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: ""
