apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  TELEGRAM_BOT_NAME: "{{ .Values.ut_telegram_bot_name }}"
  TELEGRAM_BOT_TOKEN: "{{ .Values.ut_telegram_bot_token }}"
  ACTIVITY_API_BASE_URL: "{{ .Values.activity_api_base_url }}"
  STORY_API_BASE_URL: "{{ .Values.story_api_base_url }}"
  LOG_LEVEL: "{{ .Values.ut_log_level }}"
  concurrent_updates: "{{ .Values.ut_concurrent_updates }}"
  pool_timeout: "{{ .Values.ut_pool_timeout }}"
  connection_pool_size: "{{ .Values.ut_connection_pool_size }}"
  SERVICE_ENVIRONMENT: "{{ .Values.environment }}"
  TELEMETRY_ENDPOINT_URL: "{{ .Values.telemetry_url }}"
  TELEMETRY_LOG_ENABLED: "{{ .Values.telemetry_log_enabled }}"
  SUPPORTED_LANGUAGES: "{{ .Values.ut_supported_languages }}"
  TELEGRAM_BASE_URL: "{{ .Values.ut_telegram_base_url }}"
  UVICORN_WORKERS: "{{ .Values.ut_uvicorn_workers }}"
  connect_timeout: "{{ .Values.ut_connect_timeout }}"
  read_timeout: "{{ .Values.ut_read_timeout }}"
  write_time_out: "{{ .Values.ut_write_time_out }}"