### Default variable file for webstatic-service ###
namespace: ""
imagepullsecrets: ""
dockerhub: ""

sw_repository: "djp_dashboard"
sw_image_tag: "latest"
telemetry_host: "http://telemetry-service:9001/v1"
superset_api_token: ""
superset_host: ""
dashboard_ids: "" # Array of values

replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 80
  targetport: 8080
strategy:
  type: RollingUpdate
  maxsurge: 25
  maxunavailable: 25


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: ""
